#NO USAR COMILLAS, si tiene '' no reconococe la propiedad
#Ya
sonar.projectKey=lks-ot-i-plus-d_mattin-ai
sonar.organization=lks-ot-i-plus-d
sonar.sourceEncoding=UTF-8
sonar.sources=backend
sonar.test=tests

sonar.python.coverage.reportPaths=/app/coverage.xml 
sonar.sca.exclusions=uv.lock,backend/requirements*.txt,deploy/templates/client-template/frontend/package.json,deploy/templates/client-template/hello-world-plugin/package.json
sonar.exclusions=**/alembic/**,**/migrations/**,**/scripts/**,**/__pycache__/** 
